# Generated by Django 3.2 on 2021-04-07 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='item_id',
            new_name='item',
        ),
    ]
