# Generated by Django 3.2 on 2021-04-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_rename_item_id_purchase_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_amount',
            field=models.FloatField(default=0),
        ),
    ]
